services:
  postgres:
    image: postgres:16
    container_name: mlflow_postgres
    restart: always
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow123
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: stocks-prediction-mlflow
    container_name: mlflow_server
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri postgresql://mlflow:mlflow123@postgres:5432/mlflow_db
      --serve-artifacts
      --artifacts-destination /mlflow/mlruns
      --host 0.0.0.0
      --allowed-hosts mlflow,mlflow:5000,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000

  fastapi:
    build:
      context: .
      dockerfile: app/DockerFile
    container_name: prediction_api
    restart: always
    depends_on:
      - mlflow
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MODEL_NAME: bbca-xgboost-predictor
      MODEL_ALIAS: champion
    volumes:
      - ./mlruns:/mlflow/mlruns

volumes:
  postgres_data:
